{{- if .Values.auth.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "auth.serviceAccountName" . }}
  labels:
{{ include "rafiki.labels" . | indent 4 }}
{{- end -}}
