apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.name" . }}
  labels:
{{ include "rafiki.labels" . | indent 4 }}
data: 
  NODE_ENV: development
  LOG_LEVEL: debug
  ADMIN_PORT: "{{ .Values.backend.adminPort }}"
  CONNECTOR_PORT: "{{ .Values.backend.connectorPort }}"
  OPEN_PAYMENTS_PORT: "{{ .Values.backend.openPaymentsPort }}"
  USE_TIGERBEETLE: "false"
  TIGERBEETLE_CLUSTER_ID: none
  TIGERBEETLE_REPLICA_ADDRESSES: none
