{{- if .Values.backend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "backend.serviceAccountName" . }}
  labels:
{{ include "rafiki.labels" . | indent 4 }}
{{- end -}}
