apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.name" . }}
  labels: 
{{ include "rafiki.labels" . | indent 4 }}
data: 
  GRAPHQL_URL: {{ include "frontend.graphqlUrl" . | quote }}
  LOG_LEVEL: debug
  NODE_ENV: development
  PORT: "{{ .Values.frontend.port }}"
