#CREATE USER backend PASSWORD 'changeme';
#CREATE DATABASE backend OWNER backend;

backend:
  serviceUrls:
    ILP_ADDRESS: test.cloud-nine-wallet
    PUBLIC_HOST: http://rafiki-backend
    OPEN_PAYMENTS_URL: http://rafiki-backend
    PAYMENT_POINTER_URL: http://rafiki-backend/.well-known/pay
    WEBHOOK_URL: http://cloud-nine-wallet/webhooks
    PRICES_URL: http://cloud-nine-wallet/prices
    QUOTE_URL: http://cloud-nine-wallet/quotes
  postgresql:
    host: "postgres.example.com"
    port: 5432
    username: "backend"
    database: "backend"
    password: "overridethisValue"
  openPaymentsPort: 80
  adminPort: 3001
  image:
    repository: ghcr.io/interledger/rafiki-backend
    tag: 'main'
    digest: ''
    pullPolicy: IfNotPresent
  rollingUpdate:
    maxSurge: 100%
    maxUnavailable: 50%
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ''
  securityContext:
    {}
#  resources:
#    limits:
#      memory: 1Gi
#      cpu: 450m
#    requests:
#      memory: 800Mi
#      cpu: 300m

auth:
  redis:
    host: 'redis.example.com'
    port: 6739
    databaseIndex: 0
  postgresql:
    host: "postgres.example.com"
    port: 5432
    username: "auth"
    database: "auth"
    password: "overridethisValue"
  port: 3006
  image:
    repository: ghcr.io/interledger/rafiki-auth
    tag: 'v1.0.0-alpha'
    digest: ''
    pullPolicy: IfNotPresent
  rollingUpdate:
    maxSurge: 100%
    maxUnavailable: 50%
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ''
  securityContext:
    {}
#  resources:
#    limits:
#      memory: 1Gi
#      cpu: 450m
#    requests:
#      memory: 800Mi
#      cpu: 300m
