CREATE USER backend;
CREATE DATABASE backend;
GRANT ALL ON DATABASE backend TO backend WITH GRANT OPTION;

CREATE USER auth;
CREATE DATABASE auth;
GRANT ALL ON DATABASE auth TO auth WITH GRANT OPTION;

CREATE USER peerbackend;
CREATE DATABASE peerbackend;
GRANT ALL ON DATABASE peerbackend TO peerbackend WITH GRANT OPTION;

CREATE USER peerauth;
CREATE DATABASE peerauth;
GRANT ALL ON DATABASE peerauth TO peerauth WITH GRANT OPTION;
